### ISSUE TITLE
Version de GAMA ?

### ISSUE THREAD

**Issue by benoitgaudou** [diallitoz/TPE2017#1]
Je me demande quelle version de GAMA tu utilises.
J'ai l'impression que tu utilise GAMA 1.6.1, qui commence à être un peu vieille.

N'hésite pas à passer à GAMA 1.7.

Tu devras faire quelques petites corrections : 
- définition de la constante size avec : 
int size const: true <- 2;
- ne pas avoir d'espace entre le nom d'une facet et le : ensuite.

Benoit

**Comment by diallitoz** [comment]
Bonjour M. GAUDOU,

Oui effectivement, c’est la version 1.6.1. Cela s’explique principalement par le fait que nous utilisons actuellement cette version pour les TP du module Modélisation des systèmes complexes.

Mais, je peux basculer vers la version 1.7. Pas de soucis, si c’est plus avantageux.

Merci pour vos remarques. Je vais les intégrer.

 

Très cordialement,

 

Azise

 

 

 

De : benoitgaudou [mailto:notifications@github.com] 
Envoyé : Saturday, November 11, 2017 00:19
À : diallitoz/TPE2017
Cc : Subscribed
Objet : [diallitoz/TPE2017] Version de GAMA ? (#1)

 

Je me demande quelle version de GAMA tu utilises.
J'ai l'impression que tu utilise GAMA 1.6.1, qui commence à être un peu vieille.

N'hésite pas à passer à GAMA 1.7.

Tu devras faire quelques petites corrections :

*	définition de la constante size avec :
int size const: true <- 2;
*	ne pas avoir d'espace entre le nom d'une facet et le : ensuite.

Benoit

**Comment by diallitoz** [comment]
Bonjour,
J'ai pu passer finalement a GAMA1.7. J'avais quelques petites difficultés avec mon PC (Ubuntu) pour travailler avec cette version.
J'ai créé un autre dépôt dont je vous ai mis en collaboration (TPE2017Azise). 
Merci et agréable journée.

Très cordialement,
Azise
